[general]
bars = 0
framerate = 60
autosens = 1
sensitivity = 100
lower_cutoff_freq = 50
higher_cutoff_freq = 10000

[input]
method = pulse
source = auto

[output]
method = ncurses
channels = stereo
mono_option = average
reverse = 0

[color]
background = '{{ background }}'
foreground = '{{ color1 }}'


[smoothing]
integral = 77
gravity = 100
ignore = 0
